entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          scheme: "https"
          to: "https"
          permanent: true

  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

  file:
    filename: "/etc/traefik/dynamic.yml"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "atajanovkamronbek2003@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "http"

api:
  insecure: true

log:
  level: DEBUG
